all:
	g++ -std=c++11 -o ../bin/stm.out test.cpp stm.cpp column.cpp cell.cpp inputEntry.cpp
run:
	../bin/stm.out
debug:
	g++ -std=c++11 -g -o ../bin/stm.out test.cpp stm.cpp column.cpp cell.cpp inputEntry.cpp
	gdb ../bin/stm.out
